Feature/calendar grid
benyaming/zmanim_site pull request #15
Opened 2022-04-28 08:33 UTC by bonusrk

2022-04-28 18:40 UTC, vorant94 requested changes

2022-04-28 18:40 UTC, vorant94 commented on src/app/core/state/calendar/calendar.state.ts
> +  private toggleCalendarModel(ctx: StateContext<CalendarStateModel>): void {
typo toggleCalendarModel -> toggleCalendarMode

2022-04-28 18:40 UTC, vorant94 commented on src/app/app-routing.module.ts
> +  imports: [RouterModule.forRoot(routes, { useHash: false })],
need to update nginx conf accordingly

2022-04-28 18:40 UTC, vorant94 commented on src/app/calendar/calendar-header/calendar-header.component.html
> +  <span>{{ hebrewMode ? 'Hebrew':'Gregorian' }}</span>
maybe async pipe? (then there is no need to manage subs in ts)

2022-04-28 18:54 UTC, Feviad approved these changes

2022-05-03 07:38 UTC, vorant94 commented
это по идее можно деклаинить с учетом перехода на реакт, так?

2022-05-04 04:52 UTC, closed without merging